#!/usr/bin/env bash
# Install nginx and print out the string "Hello World!"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
