#!/usr/bin/env bash
#Configuring a brand new Ubuntu machine

apt-get update
apt-get install -y nginx

printf %s "server {
  listen      80 default_server;
  add_header  X-Served-By $HOSTNAME;
  root        /var/www/html;
  index       index.html index.htm;
  location /redirect_me {
    return 301 http://github.com/prohence;
  }
  error_page 404 /404.html;
  location = /404.html {
    root /var/www/html/;
    internal;
  }
}
" >/etc/nginx/sites-available/default
echo "Hello school!" >/var/www/html/index.html
printf "%s\n" "Ceci n'est pas une page" >/var/www/html/404.html
service nginx restart
